# GeneralsX @feature GeneralsOnline NGMP protocol dependency setup
# Integrates nlohmann_json, libcurl, and cross-platform networking primitives.

if(SAGE_USE_NGMP)
    find_package(nlohmann_json QUIET)
    if(NOT nlohmann_json_FOUND AND NOT FETCHCONTENT_FULLY_DISCONNECTED)
        include(FetchContent)
        FetchContent_Declare(
            json
            URL https://github.com/nlohmann/json/releases/download/v3.11.3/json.tar.xz
        )
        FetchContent_MakeAvailable(json)
    endif()

    find_package(CURL REQUIRED)
    find_package(GameNetworkingSockets QUIET)

    set(_PROTOBUF_BREW_PREFIX "")
    if(APPLE)
        if(EXISTS "/opt/homebrew/opt/protobuf@29")
            set(_PROTOBUF_BREW_PREFIX "/opt/homebrew/opt/protobuf@29")
        elseif(EXISTS "/opt/homebrew/opt/protobuf")
            set(_PROTOBUF_BREW_PREFIX "/opt/homebrew/opt/protobuf")
        elseif(EXISTS "/usr/local/opt/protobuf")
            set(_PROTOBUF_BREW_PREFIX "/usr/local/opt/protobuf")
        endif()
    endif()

    set(_HAS_PROTOBUF FALSE)
    if(_PROTOBUF_BREW_PREFIX)
        set(_HAS_PROTOBUF TRUE)
        set(Protobuf_ROOT "${_PROTOBUF_BREW_PREFIX}" CACHE PATH "" FORCE)
        set(Protobuf_INCLUDE_DIR "${_PROTOBUF_BREW_PREFIX}/include" CACHE PATH "" FORCE)
        set(Protobuf_INCLUDE_DIRS "${_PROTOBUF_BREW_PREFIX}/include" CACHE PATH "" FORCE)
        set(Protobuf_LIBRARY "${_PROTOBUF_BREW_PREFIX}/lib/libprotobuf.dylib" CACHE FILEPATH "" FORCE)
        set(Protobuf_LIBRARIES "${_PROTOBUF_BREW_PREFIX}/lib/libprotobuf.dylib" CACHE FILEPATH "" FORCE)
        set(Protobuf_PROTOC_EXECUTABLE "${_PROTOBUF_BREW_PREFIX}/bin/protoc" CACHE FILEPATH "" FORCE)
        set(CMAKE_PREFIX_PATH "${_PROTOBUF_BREW_PREFIX};/opt/homebrew;${CMAKE_PREFIX_PATH}" CACHE STRING "" FORCE)
        set(CMAKE_NO_SYSTEM_FROM_IMPORTED ON)
        include_directories(BEFORE "${_PROTOBUF_BREW_PREFIX}/include")
    else()
        find_package(Protobuf QUIET)
        if(Protobuf_FOUND)
            set(_HAS_PROTOBUF TRUE)
        endif()
    endif()

    if(NOT GameNetworkingSockets_FOUND AND NOT TARGET GameNetworkingSockets AND NOT TARGET GameNetworkingSockets::GameNetworkingSockets AND NOT FETCHCONTENT_FULLY_DISCONNECTED AND _HAS_PROTOBUF)
        include(FetchContent)
        set(BUILD_TESTS OFF CACHE BOOL "" FORCE)
        set(BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
        set(BUILD_TOOLS OFF CACHE BOOL "" FORCE)
        if(WIN32)
            set(USE_CRYPTO "BCrypt" CACHE STRING "" FORCE)
        else()
            set(USE_CRYPTO "OpenSSL" CACHE STRING "" FORCE)
        endif()
        set(ENABLE_ICE ON CACHE BOOL "" FORCE)
        set(USE_STEAMWEBRTC OFF CACHE BOOL "" FORCE)
        FetchContent_Declare(
            GameNetworkingSockets
            GIT_REPOSITORY https://github.com/ValveSoftware/GameNetworkingSockets.git
            GIT_TAG v1.4.1
            GIT_SHALLOW TRUE
            GIT_SUBMODULES ""
        )
        FetchContent_MakeAvailable(GameNetworkingSockets)
        if(TARGET GameNetworkingSockets)
            set_target_properties(GameNetworkingSockets PROPERTIES CXX_STANDARD 17)
            if(_PROTOBUF_BREW_PREFIX)
                target_include_directories(GameNetworkingSockets BEFORE PUBLIC "${_PROTOBUF_BREW_PREFIX}/include")
                target_link_libraries(GameNetworkingSockets PRIVATE "${_PROTOBUF_BREW_PREFIX}/lib/libprotobuf.dylib")
            endif()
        endif()
        if(TARGET GameNetworkingSockets_s)
            set_target_properties(GameNetworkingSockets_s PROPERTIES CXX_STANDARD 17)
            if(_PROTOBUF_BREW_PREFIX)
                target_include_directories(GameNetworkingSockets_s BEFORE PUBLIC "${_PROTOBUF_BREW_PREFIX}/include")
                target_link_libraries(GameNetworkingSockets_s PRIVATE "${_PROTOBUF_BREW_PREFIX}/lib/libprotobuf.dylib")
            endif()
        endif()
    endif()

    if(_PROTOBUF_BREW_PREFIX)
        target_include_directories(core_config BEFORE INTERFACE "${_PROTOBUF_BREW_PREFIX}/include")
    endif()

    if(TARGET nlohmann_json::nlohmann_json)
        target_link_libraries(core_config INTERFACE nlohmann_json::nlohmann_json)
    elseif(TARGET nlohmann_json)
        target_link_libraries(core_config INTERFACE nlohmann_json)
    endif()

    if(TARGET GameNetworkingSockets::GameNetworkingSockets)
        target_link_libraries(core_config INTERFACE GameNetworkingSockets::GameNetworkingSockets)
        target_compile_definitions(core_config INTERFACE SAGE_USE_GAMENETWORKINGSOCKETS=1)
    elseif(TARGET GameNetworkingSockets)
        target_link_libraries(core_config INTERFACE GameNetworkingSockets)
        target_compile_definitions(core_config INTERFACE SAGE_USE_GAMENETWORKINGSOCKETS=1)
    elseif(TARGET GameNetworkingSockets_s)
        target_link_libraries(core_config INTERFACE GameNetworkingSockets_s)
        target_compile_definitions(core_config INTERFACE SAGE_USE_GAMENETWORKINGSOCKETS=1)
    endif()

    if(DEFINED gamenetworkingsockets_SOURCE_DIR)
        target_include_directories(core_config INTERFACE ${gamenetworkingsockets_SOURCE_DIR}/include)
    endif()

    target_link_libraries(core_config INTERFACE ${CURL_LIBRARIES})
    target_include_directories(core_config INTERFACE ${CURL_INCLUDE_DIRS})

    # NGMP Server Host & Port configuration (File > Environment > Default)
    if(EXISTS "${CMAKE_SOURCE_DIR}/cmake/ngmp_env.cmake")
        include("${CMAKE_SOURCE_DIR}/cmake/ngmp_env.cmake")
    endif()

    if(EXISTS "${CMAKE_SOURCE_DIR}/.ngmp-config.cmake")
        include("${CMAKE_SOURCE_DIR}/.ngmp-config.cmake")
    endif()

    if(EXISTS "${CMAKE_SOURCE_DIR}/.ngmp-server-host")
        file(READ "${CMAKE_SOURCE_DIR}/.ngmp-server-host" NGMP_SERVER_HOST)
        string(STRIP "${NGMP_SERVER_HOST}" NGMP_SERVER_HOST)
        set(NGMP_SERVER_HOST "${NGMP_SERVER_HOST}" CACHE STRING "NGMP Server Host" FORCE)
    elseif(DEFINED ENV{NGMP_SERVER_HOST} AND NOT "$ENV{NGMP_SERVER_HOST}" STREQUAL "")
        set(NGMP_SERVER_HOST "$ENV{NGMP_SERVER_HOST}" CACHE STRING "NGMP Server Host" FORCE)
    elseif(DEFINED ENV{NGMP_DEFAULT_HOST} AND NOT "$ENV{NGMP_DEFAULT_HOST}" STREQUAL "")
        set(NGMP_SERVER_HOST "$ENV{NGMP_DEFAULT_HOST}" CACHE STRING "NGMP Server Host" FORCE)
    elseif(DEFINED NGMP_SERVER_HOST AND NOT "${NGMP_SERVER_HOST}" STREQUAL "")
        set(NGMP_SERVER_HOST "${NGMP_SERVER_HOST}" CACHE STRING "NGMP Server Host" FORCE)
    elseif(DEFINED NGMP_DEFAULT_HOST AND NOT "${NGMP_DEFAULT_HOST}" STREQUAL "")
        set(NGMP_SERVER_HOST "${NGMP_DEFAULT_HOST}" CACHE STRING "NGMP Server Host" FORCE)
    else()
        set(NGMP_SERVER_HOST "localhost" CACHE STRING "NGMP Server Host")
    endif()

    if(DEFINED ENV{NGMP_SERVER_PORT} AND NOT "$ENV{NGMP_SERVER_PORT}" STREQUAL "")
        set(NGMP_SERVER_PORT "$ENV{NGMP_SERVER_PORT}" CACHE STRING "NGMP Server Port" FORCE)
    elseif(NOT DEFINED NGMP_SERVER_PORT OR "${NGMP_SERVER_PORT}" STREQUAL "")
        set(NGMP_SERVER_PORT "9001" CACHE STRING "NGMP Server Port")
    endif()

    if(DEFINED ENV{NGMP_USE_SSL} AND NOT "$ENV{NGMP_USE_SSL}" STREQUAL "")
        if("$ENV{NGMP_USE_SSL}" MATCHES "^(1|ON|YES|TRUE|Y|on|yes|true|y)$")
            option(NGMP_USE_SSL "Enable SSL for NGMP protocol" ON)
        else()
            option(NGMP_USE_SSL "Enable SSL for NGMP protocol" OFF)
        endif()
    elseif(NOT DEFINED NGMP_USE_SSL)
        option(NGMP_USE_SSL "Enable SSL for NGMP protocol" OFF)
    endif()

    target_compile_definitions(core_config INTERFACE
        NGMP_DEFAULT_HOST="${NGMP_SERVER_HOST}"
        NGMP_DEFAULT_PORT="${NGMP_SERVER_PORT}"
    )

    if(NGMP_USE_SSL)
        target_compile_definitions(core_config INTERFACE NGMP_USE_SSL=1)
        message(STATUS "NGMP: Server target configured to wss://${NGMP_SERVER_HOST}:${NGMP_SERVER_PORT}")
    else()
        target_compile_definitions(core_config INTERFACE NGMP_USE_SSL=0)
        message(STATUS "NGMP: Server target configured to ws://${NGMP_SERVER_HOST}:${NGMP_SERVER_PORT}")
    endif()

    message(STATUS "NGMP: nlohmann_json and libcurl configured successfully")
endif()
